"""Value objects used by the autonomous research loop."""

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class Metrics:
    """Validation metrics used for candidate selection."""

    gauc: float
    ndcg_at_5: float
    primary: float


@dataclass(frozen=True, slots=True)
class CodeEdit:
    """One exact replacement generated by the coding model."""

    file: str
    old: str
    new: str


@dataclass(frozen=True, slots=True)
class Plan:
    """One model-generated code-search action."""

    action: str
    parent_id: str
    title: str
    hypothesis: str
    stop_rule: str
    edits: tuple[CodeEdit, ...]


@dataclass(frozen=True, slots=True)
class Execution:
    """Captured result of one candidate subprocess."""

    output: str
    seconds: float


@dataclass(frozen=True, slots=True)
class CandidateAttempt:
    """Result of an initial candidate run and optional automatic repair."""

    source: str
    metrics: Metrics | None
    execution: Execution | None
    command: tuple[str, ...]
    recovery_events: tuple[str, ...]
    input_tokens: int
    output_tokens: int


@dataclass(frozen=True, slots=True)
class Node:
    """A solution-tree node and its measured validation score."""

    node_id: str
    parent_id: str | None
    code_path: Path
    output_directory: Path | None
    metrics: Metrics | None
    status: str
    depth: int
    title: str = ""
    hypothesis: str = ""


@dataclass(frozen=True, slots=True)
class AgentSummary:
    """Final state of one autonomous search."""

    best_validation: Metrics
    iterations: int
    manual_interventions: int
    total_input_tokens: int
    total_output_tokens: int
    run_directory: Path
    final_submission: Path | None


@dataclass(slots=True)
class SearchState:
    """Mutable state for the best-first solution-tree search."""

    baseline: Metrics
    runtime_baseline: Metrics
    best: Node
    nodes: dict[str, Node]
    scores: list[float]


@dataclass(frozen=True, slots=True)
class IterationOutcome:
    """Planner and candidate result for one search iteration."""

    attempted: bool
    input_tokens: int
    output_tokens: int
    stop_reason: str | None
