"""AIDE-style autonomous code search for the KuaiRand benchmark."""

import difflib
import json
import os
import re
import shutil
import subprocess
import sys
import time
from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path

from openai import APIError, OpenAI

from kopibara_agent.agent import ModelAnswer, ask_model_with_usage

CONVERGENCE_EPSILON = 0.002
CONVERGENCE_WINDOW = 3
MAX_CODE_EDITS = 4
MAX_PLANNER_ATTEMPTS = 2
CANDIDATE_SEED = 0
CANDIDATE_SOURCE = Path("experiments/history_lgbm.py")
CANDIDATE_SCRIPT = "history_lgbm.py"
STOP_ACTION = "stop"
EDIT_ACTION = "edit"
DANGEROUS_CODE_TOKENS = (
    "subprocess",
    "socket",
    "requests",
    "urllib",
    "httpx",
    "openai",
    "os.system",
    "eval(",
    "exec(",
    "__import__",
)
METRIC_PATTERN = re.compile(
    r"valid\s+GAUC\s+(?P<gauc>[0-9.]+)\s+"
    r"nDCG@5\s+(?P<ndcg>[0-9.]+)\s+"
    r"primary\s+(?P<primary>[0-9.]+)"
)


@dataclass(frozen=True, slots=True)
class Metrics:
    """Validation metrics used for candidate selection."""

    gauc: float
    ndcg_at_5: float
    primary: float


@dataclass(frozen=True, slots=True)
class CodeEdit:
    """One exact replacement generated by the coding model."""

    file: str
    old: str
    new: str


@dataclass(frozen=True, slots=True)
class Plan:
    """One model-generated code-search action."""

    action: str
    parent_id: str
    title: str
    hypothesis: str
    stop_rule: str
    edits: tuple[CodeEdit, ...]


@dataclass(frozen=True, slots=True)
class Execution:
    """Captured result of one candidate subprocess."""

    output: str
    seconds: float


@dataclass(frozen=True, slots=True)
class CandidateAttempt:
    """Result of an initial candidate run and optional automatic repair."""

    source: str
    metrics: Metrics | None
    execution: Execution | None
    command: tuple[str, ...]
    recovery_events: tuple[str, ...]
    input_tokens: int
    output_tokens: int


@dataclass(frozen=True, slots=True)
class Node:
    """A solution-tree node and its measured validation score."""

    node_id: str
    parent_id: str | None
    code_path: Path
    output_directory: Path | None
    metrics: Metrics | None
    status: str
    depth: int
    title: str = ""
    hypothesis: str = ""


@dataclass(frozen=True, slots=True)
class AgentSummary:
    """Final state of one autonomous search."""

    best_validation: Metrics
    iterations: int
    manual_interventions: int
    total_input_tokens: int
    total_output_tokens: int
    run_directory: Path
    final_submission: Path | None


@dataclass(slots=True)
class SearchState:
    """Mutable state for the best-first solution-tree search."""

    baseline: Metrics
    runtime_baseline: Metrics
    best: Node
    nodes: dict[str, Node]
    scores: list[float]


@dataclass(frozen=True, slots=True)
class IterationOutcome:
    """Planner and candidate result for one search iteration."""

    attempted: bool
    input_tokens: int
    output_tokens: int
    stop_reason: str | None


def build_baseline_command(root: Path, data_directory: Path) -> tuple[str, ...]:
    """Build the fixed organizer-baseline command."""
    return (
        sys.executable,
        str(root / "kuairand-starter-kit" / "baseline.py"),
        "--data_dir",
        str(data_directory),
        "--model",
        "fm",
        "--seed",
        "0",
    )


def load_official_baseline(root: Path) -> Metrics:
    """Read the organizer-published validation reference from the kit."""
    metadata_path = root / "kuairand-starter-kit" / "baseline_scores.json"
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    score = metadata["scores"]["fm_official"]["valid"]
    return Metrics(
        float(score["GAUC"]),
        float(score["nDCG@5"]),
        float(score["primary"]),
    )


def parse_metrics(output: str) -> Metrics:
    """Parse only the validation line emitted by a candidate."""
    matches = list(METRIC_PATTERN.finditer(output))
    if not matches:
        raise ValueError("no validation metrics found in candidate output")
    match = matches[-1]
    return Metrics(
        gauc=float(match["gauc"]),
        ndcg_at_5=float(match["ndcg"]),
        primary=float(match["primary"]),
    )


def parse_candidate_metrics(output: str, output_directory: Path) -> Metrics:
    """Parse candidate stdout, falling back to its own metrics artifact."""
    try:
        return parse_metrics(output)
    except ValueError as output_error:
        metrics_path = output_directory / "metrics.json"
        try:
            payload = json.loads(metrics_path.read_text(encoding="utf-8"))
            valid = payload["valid"]
            return Metrics(
                gauc=float(valid["GAUC"]),
                ndcg_at_5=float(valid["nDCG@5"]),
                primary=float(valid["primary"]),
            )
        except (KeyError, OSError, TypeError, ValueError) as artifact_error:
            raise ValueError(
                f"{output_error}; metrics artifact unavailable or invalid"
            ) from artifact_error


def has_converged(
    scores: Sequence[float],
    *,
    epsilon: float = CONVERGENCE_EPSILON,
    window: int = CONVERGENCE_WINDOW,
) -> bool:
    """Apply the organizer's N consecutive small-improvement rule."""
    if len(scores) < window + 1:
        return False
    recent = scores[-(window + 1) :]
    return all(recent[index + 1] - recent[index] <= epsilon for index in range(window))


def parse_plan(raw: str, parent_ids: Sequence[str]) -> Plan:
    """Parse and validate a model plan before it can touch candidate code."""
    start = raw.find("{")
    end = raw.rfind("}")
    if start < 0 or end <= start:
        raise ValueError("planner response has no JSON object")
    payload = json.loads(raw[start : end + 1])
    if not isinstance(payload, dict):
        raise ValueError("planner response is not a JSON object")

    action = payload.get("action")
    parent_id = payload.get("parent_id")
    title = payload.get("title", "")
    hypothesis = payload.get("hypothesis", "")
    stop_rule = payload.get("stop_rule", "")
    raw_edits = payload.get("edits", [])
    if action not in (EDIT_ACTION, STOP_ACTION):
        raise ValueError("planner action must be edit or stop")
    if not isinstance(parent_id, str) or parent_id not in parent_ids:
        raise ValueError("planner selected an unknown parent")
    if not all(isinstance(value, str) for value in (title, hypothesis, stop_rule)):
        raise ValueError("planner text fields must be strings")
    if not isinstance(raw_edits, list) or len(raw_edits) > MAX_CODE_EDITS:
        raise ValueError(f"planner must return at most {MAX_CODE_EDITS} edits")

    edits: list[CodeEdit] = []
    for raw_edit in raw_edits:
        if not isinstance(raw_edit, dict):
            raise ValueError("planner edit must be an object")
        file = raw_edit.get("file")
        old = raw_edit.get("old")
        new = raw_edit.get("new")
        if (
            not isinstance(file, str)
            or not isinstance(old, str)
            or not isinstance(new, str)
        ):
            raise ValueError("planner edit fields must be strings")
        if file != CANDIDATE_SCRIPT or not old:
            raise ValueError("planner may edit history_lgbm.py only")
        edits.append(CodeEdit(file, old, new))

    if action == STOP_ACTION and edits:
        raise ValueError("stop action cannot contain edits")
    if action == EDIT_ACTION and not edits:
        raise ValueError("edit action must contain at least one edit")
    return Plan(action, parent_id, title, hypothesis, stop_rule, tuple(edits))


def apply_code_edits(source: str, edits: Sequence[CodeEdit]) -> str:
    """Apply exact, single-match replacements and reject unsafe additions."""
    result = source
    for edit in edits:
        matches = result.count(edit.old)
        if matches != 1:
            raise ValueError(f"edit must match exactly once, found {matches}")
        result = result.replace(edit.old, edit.new, 1)
    for token in DANGEROUS_CODE_TOKENS:
        if token in result and token not in source:
            raise ValueError(f"candidate adds blocked token: {token}")
    return result


def build_planner_prompt(
    baseline: Metrics,
    best: Node,
    nodes: Mapping[str, Node],
    parent: Node,
    source: str,
) -> str:
    """Give Luna task facts, tree state, and the parent code to edit."""
    tree = [
        {
            "node_id": node.node_id,
            "parent_id": node.parent_id,
            "status": node.status,
            "title": node.title,
            "hypothesis": node.hypothesis,
            "validation_primary": (
                node.metrics.primary if node.metrics is not None else None
            ),
        }
        for node in nodes.values()
    ]
    convergence = (
        f"Organizer convergence: epsilon={CONVERGENCE_EPSILON}, "
        f"consecutive rounds={CONVERGENCE_WINDOW}."
    )
    best_metrics = asdict(best.metrics) if best.metrics else None
    return f"""You are the coding agent inside an autonomous ML research run.
Task: improve KuaiRand-Pure within-user ranking. Train and validation only.
Do not use test labels or hidden-test information. The official evaluator scores
the mean of GAUC and nDCG@5. The official FM baseline uses five fields and
pointwise logloss. Candidate code must remain a runnable Python script.

{convergence}
Official baseline validation: {asdict(baseline)}
Current best node: {best.node_id}, validation: {best_metrics}
Solution tree: {json.dumps(tree)}
Parent node to improve: {parent.node_id}

Research guidance from the starter kit: the organizer already measured static
feature additions and larger FM embeddings as non-improvements. Prioritize
changes that align training with ranking metrics, exploit within-user history
or other released feedback when available, or use an established ranking
objective. Do not repeat a known dead end without a specific new hypothesis.

Return JSON only:
{{"action":"edit"|"stop","parent_id":"{parent.node_id}","title":"short",
"hypothesis":"testable reason","stop_rule":"validation rule",
"edits":[{{"file":"history_lgbm.py","old":"exact existing text",
"new":"replacement text"}}]}}

Rules:
- One focused change; at most {MAX_CODE_EDITS} exact edits.
- Edit history_lgbm.py only. Every old string must occur exactly once.
- Keep CLI arguments and final validation output intact.
- Do not add network, subprocess, shell, filesystem traversal, eval, or exec code.
- If no credible improvement remains, return action=stop with edits=[].

Parent candidate source:
```python
{source}
```
"""


def build_repair_prompt(
    plan: Plan,
    source: str,
    error: str,
    parent_id: str,
) -> str:
    """Ask Luna to repair a failed generated candidate."""
    return f"""Repair one failed candidate in a controlled ML experiment.
The candidate must remain a standalone Python script with the same CLI and
validation output. Do not use test labels or hidden-test information.
Parent node: {parent_id}
Original hypothesis: {plan.hypothesis}
Failure:
{error[-4000:]}

Return JSON only with this shape:
{{"action":"edit","parent_id":"{parent_id}","title":"repair",
"hypothesis":"repair reason","stop_rule":"stop if repair fails",
"edits":[{{"file":"history_lgbm.py","old":"exact existing text",
"new":"replacement text"}}]}}
Use at most {MAX_CODE_EDITS} exact edits, history_lgbm.py only, no new imports,
no network or subprocess calls.

Current failed source:
```python
{source}
```
"""


def run_command(
    command: Sequence[str],
    *,
    root: Path,
    timeout_seconds: float,
    environment: Mapping[str, str],
) -> Execution:
    """Run a fixed command without shell interpretation."""
    started = time.monotonic()
    completed = subprocess.run(
        list(command),
        cwd=root,
        env=dict(environment),
        capture_output=True,
        text=True,
        check=False,
        timeout=timeout_seconds,
    )
    output = completed.stdout + completed.stderr
    if completed.returncode != 0:
        raise RuntimeError(f"exit code {completed.returncode}: {output[-4000:]}")
    return Execution(output, time.monotonic() - started)


def select_parent(nodes: Mapping[str, Node]) -> Node:
    """Select the highest-scoring measured node for best-first search."""
    measured = [
        node
        for node in nodes.values()
        if node.metrics is not None and node.status != "recovered_failure"
    ]
    if not measured:
        raise ValueError("solution tree has no measured node")
    return max(
        measured,
        key=lambda node: node.metrics.primary if node.metrics else -1.0,
    )


def request_plan(
    prompt: str,
    parent_ids: Sequence[str],
    *,
    client: OpenAI | None,
) -> tuple[Plan, int, int, list[str]]:
    """Request valid JSON twice at most and return all recovery errors."""
    errors: list[str] = []
    input_tokens = 0
    output_tokens = 0
    for _ in range(MAX_PLANNER_ATTEMPTS):
        try:
            answer: ModelAnswer = ask_model_with_usage(prompt, client=client)
            input_tokens += answer.input_tokens
            output_tokens += answer.output_tokens
            return (
                parse_plan(answer.text, parent_ids),
                input_tokens,
                output_tokens,
                errors,
            )
        except (APIError, ValueError) as error:
            errors.append(str(error))
    raise RuntimeError("planner failed after retries: " + " | ".join(errors))


def write_log(path: Path, record: Mapping[str, object]) -> None:
    """Write a complete iteration record."""
    path.write_text(
        json.dumps(record, indent=2, default=str) + "\n",
        encoding="utf-8",
    )


def build_environment(root: Path) -> dict[str, str]:
    """Give candidates project location without forwarding the API key."""
    environment = os.environ.copy()
    environment.pop("OPENAI_API_KEY", None)
    environment["KUAI_PROJECT_ROOT"] = str(root)
    return environment


def build_candidate_command(
    code_path: Path,
    data_directory: Path,
    output_directory: Path,
) -> tuple[str, ...]:
    """Build the only candidate command the controller can execute."""
    return (
        sys.executable,
        str(code_path),
        "--data-dir",
        str(data_directory),
        "--objective",
        "lambdarank",
        "--feedbacks",
        "all",
        "--seed",
        str(CANDIDATE_SEED),
        "--output-dir",
        str(output_directory),
    )


def run_candidate(
    code_path: Path,
    data_directory: Path,
    output_directory: Path,
    *,
    root: Path,
    environment: Mapping[str, str],
    timeout_seconds: float,
) -> tuple[Execution, tuple[str, ...]]:
    """Compile and execute one candidate with a bounded timeout."""
    compile_command = (sys.executable, "-m", "py_compile", str(code_path))
    compile_execution = run_command(
        compile_command,
        root=root,
        timeout_seconds=timeout_seconds,
        environment=environment,
    )
    command = build_candidate_command(code_path, data_directory, output_directory)
    execution = run_command(
        command,
        root=root,
        timeout_seconds=timeout_seconds,
        environment=environment,
    )
    return (
        Execution(
            execution.output,
            compile_execution.seconds + execution.seconds,
        ),
        command,
    )


def attempt_candidate(
    plan: Plan,
    parent: Node,
    parent_source: str,
    child_code: Path,
    child_output: Path,
    *,
    root: Path,
    data_directory: Path,
    environment: Mapping[str, str],
    timeout_seconds: float,
    client: OpenAI | None,
) -> CandidateAttempt:
    """Apply, run, and repair one generated child candidate."""
    recovery_events: list[str] = []
    input_tokens = 0
    output_tokens = 0
    source = parent_source
    command = build_candidate_command(child_code, data_directory, child_output)
    try:
        source = apply_code_edits(parent_source, plan.edits)
        child_code.write_text(source, encoding="utf-8")
        execution, command = run_candidate(
            child_code,
            data_directory,
            child_output,
            root=root,
            environment=environment,
            timeout_seconds=timeout_seconds,
        )
        return CandidateAttempt(
            source,
            parse_candidate_metrics(execution.output, child_output),
            execution,
            command,
            tuple(recovery_events),
            input_tokens,
            output_tokens,
        )
    except (OSError, RuntimeError, ValueError, subprocess.TimeoutExpired) as error:
        recovery_events.append(str(error))

    repair_prompt = build_repair_prompt(
        plan,
        parent_source,
        recovery_events[-1],
        parent.node_id,
    )
    try:
        repair_plan, repair_input, repair_output, repair_errors = request_plan(
            repair_prompt,
            (parent.node_id,),
            client=client,
        )
        input_tokens += repair_input
        output_tokens += repair_output
        source = apply_code_edits(parent_source, repair_plan.edits)
        child_code.write_text(source, encoding="utf-8")
        execution, command = run_candidate(
            child_code,
            data_directory,
            child_output,
            root=root,
            environment=environment,
            timeout_seconds=timeout_seconds,
        )
        recovery_events.extend(repair_errors)
        recovery_events.append("candidate repaired and rerun")
        return CandidateAttempt(
            source,
            parse_candidate_metrics(execution.output, child_output),
            execution,
            command,
            tuple(recovery_events),
            input_tokens,
            output_tokens,
        )
    except (
        APIError,
        OSError,
        RuntimeError,
        ValueError,
        subprocess.TimeoutExpired,
    ) as error:
        recovery_events.append(f"repair failed: {error}")
        return CandidateAttempt(
            source,
            None,
            None,
            command,
            tuple(recovery_events),
            input_tokens,
            output_tokens,
        )


def copy_best(node: Node, run_directory: Path) -> tuple[Path, Path | None]:
    """Copy the best code and available model artifacts to stable paths."""
    best_code = run_directory / "best_solution.py"
    shutil.copy2(node.code_path, best_code)
    if node.output_directory is None:
        return best_code, None
    best_output = run_directory / "best_output"
    if best_output.exists():
        shutil.rmtree(best_output)
    shutil.copytree(node.output_directory, best_output)
    return best_code, best_output


def finalize_submission(
    best: Node,
    run_directory: Path,
    *,
    root: Path,
    data_directory: Path,
    environment: Mapping[str, str],
    timeout_seconds: float,
) -> Path | None:
    """Create and validate the final aligned submission."""
    _, best_output = copy_best(best, run_directory)
    submission_path = run_directory / "submission.csv"
    if best_output is None:
        command = (
            sys.executable,
            str(root / "kuairand-starter-kit" / "submit.py"),
            "--data_dir",
            str(data_directory),
            "--split",
            "test",
            "--make",
            str(submission_path),
        )
    else:
        command = (
            sys.executable,
            str(root / "experiments" / "write_submission.py"),
            "--data-dir",
            str(data_directory),
            "--scores",
            str(best_output / "test_scores.npy"),
            "--output",
            str(submission_path),
        )
    run_command(
        command,
        root=root,
        timeout_seconds=timeout_seconds,
        environment=environment,
    )
    check_command = (
        sys.executable,
        str(root / "kuairand-starter-kit" / "submit.py"),
        "--data_dir",
        str(data_directory),
        "--split",
        "test",
        "--check",
        str(submission_path),
    )
    run_command(
        check_command,
        root=root,
        timeout_seconds=timeout_seconds,
        environment=environment,
    )
    return submission_path


def initialize_search(
    root: Path,
    data_directory: Path,
    run_directory: Path,
    node_directory: Path,
    *,
    environment: Mapping[str, str],
    timeout_seconds: float,
) -> SearchState:
    """Verify the official baseline and measure the initial candidate node."""
    baseline_execution = run_command(
        build_baseline_command(root, data_directory),
        root=root,
        timeout_seconds=timeout_seconds,
        environment=environment,
    )
    runtime_baseline = parse_metrics(baseline_execution.output)
    baseline = load_official_baseline(root)
    root_directory = node_directory / "000-root"
    root_code = root_directory / CANDIDATE_SCRIPT
    root_output = root_directory / "output"
    root_directory.mkdir(parents=True, exist_ok=True)
    shutil.copy2(root / CANDIDATE_SOURCE, root_code)
    root_execution, root_command = run_candidate(
        root_code,
        data_directory,
        root_output,
        root=root,
        environment=environment,
        timeout_seconds=timeout_seconds,
    )
    root_metrics = parse_candidate_metrics(root_execution.output, root_output)
    root_node = Node("000-root", None, root_code, root_output, root_metrics, "kept", 0)
    best = (
        root_node
        if root_metrics.primary > baseline.primary
        else Node(
            "baseline",
            None,
            root / "kuairand-starter-kit" / "baseline.py",
            None,
            baseline,
            "baseline",
            0,
        )
    )
    write_log(
        run_directory / "000_root.json",
        {
            "iteration": 0,
            "status": "kept",
            "node_id": root_node.node_id,
            "parent_id": None,
            "baseline_validation": asdict(baseline),
            "runtime_baseline_validation": asdict(runtime_baseline),
            "validation": asdict(root_metrics),
            "seconds": baseline_execution.seconds + root_execution.seconds,
            "command": list(root_command),
            "code_diff": "seed candidate copied from experiments/history_lgbm.py",
            "manual_interventions": 0,
            "hidden_test_access": False,
        },
    )
    return SearchState(
        baseline,
        runtime_baseline,
        best,
        {root_node.node_id: root_node},
        [baseline.primary, root_metrics.primary],
    )


def run_search_iteration(
    iteration: int,
    state: SearchState,
    run_directory: Path,
    node_directory: Path,
    *,
    root: Path,
    data_directory: Path,
    environment: Mapping[str, str],
    timeout_seconds: float,
    client: OpenAI | None,
) -> IterationOutcome:
    """Plan, execute, recover, score, and log one tree-search child."""
    parent = select_parent(state.nodes)
    parent_source = parent.code_path.read_text(encoding="utf-8")
    prompt = build_planner_prompt(
        state.baseline,
        state.best,
        state.nodes,
        parent,
        parent_source,
    )
    try:
        plan, used_input, used_output, planner_errors = request_plan(
            prompt,
            (parent.node_id,),
            client=client,
        )
    except RuntimeError as error:
        write_log(
            run_directory / f"{iteration:03d}_planner_failure.json",
            {
                "iteration": iteration,
                "status": "recovered_planner_failure",
                "error": str(error),
                "manual_interventions": 0,
                "hidden_test_access": False,
            },
        )
        return IterationOutcome(False, 0, 0, "planner_failure")
    if plan.action == STOP_ACTION:
        write_log(
            run_directory / f"{iteration:03d}_stop.json",
            {
                "iteration": iteration,
                "status": "stopped_by_agent",
                "plan": asdict(plan),
                "planner_recovery": planner_errors,
                "manual_interventions": 0,
                "hidden_test_access": False,
            },
        )
        return IterationOutcome(False, used_input, used_output, "agent_stop")

    node_id = f"{iteration:03d}-child"
    child_directory = node_directory / node_id
    child_directory.mkdir(parents=True, exist_ok=True)
    child_code = child_directory / CANDIDATE_SCRIPT
    child_output = child_directory / "output"
    attempt = attempt_candidate(
        plan,
        parent,
        parent_source,
        child_code,
        child_output,
        root=root,
        data_directory=data_directory,
        environment=environment,
        timeout_seconds=timeout_seconds,
        client=client,
    )
    node_status = "evaluated" if attempt.metrics is not None else "recovered_failure"
    node = Node(
        node_id,
        parent.node_id,
        child_code,
        child_output if attempt.metrics is not None else None,
        attempt.metrics,
        node_status,
        parent.depth + 1,
        plan.title,
        plan.hypothesis,
    )
    state.nodes[node_id] = node
    is_best = attempt.metrics is not None and (
        state.best.metrics is None
        or attempt.metrics.primary > state.best.metrics.primary
    )
    if is_best:
        state.best = node
        copy_best(node, run_directory)
    fallback_score = state.best.metrics.primary if state.best.metrics else -1.0
    state.scores.append(
        attempt.metrics.primary if attempt.metrics is not None else fallback_score
    )
    diff = "".join(
        difflib.unified_diff(
            parent_source.splitlines(keepends=True),
            attempt.source.splitlines(keepends=True),
            fromfile=parent.node_id,
            tofile=node_id,
        )
    )
    write_log(
        run_directory / f"{iteration:03d}_{node_id}.json",
        {
            "iteration": iteration,
            "node_id": node_id,
            "parent_id": parent.node_id,
            "plan": asdict(plan),
            "status": "kept" if is_best else node.status,
            "validation": asdict(attempt.metrics) if attempt.metrics else None,
            "seconds": attempt.execution.seconds if attempt.execution else None,
            "command": list(attempt.command),
            "code_diff": diff,
            "recovery_events": attempt.recovery_events,
            "planner_recovery": planner_errors,
            "input_tokens": attempt.input_tokens + used_input,
            "output_tokens": attempt.output_tokens + used_output,
            "manual_interventions": 0,
            "hidden_test_access": False,
        },
    )
    return IterationOutcome(
        True,
        used_input + attempt.input_tokens,
        used_output + attempt.output_tokens,
        None,
    )


def build_manifest(
    state: SearchState,
    *,
    root: Path,
    stopped_reason: str,
    attempted: int,
    max_iterations: int,
    elapsed_seconds: float,
    input_tokens: int,
    output_tokens: int,
    final_submission: Path | None,
) -> dict[str, object]:
    """Build the reproducibility and judging manifest."""
    return {
        "status": "completed",
        "stopped_reason": stopped_reason,
        "baseline_validation": asdict(state.baseline),
        "runtime_baseline_validation": asdict(state.runtime_baseline),
        "best_validation": asdict(state.best.metrics) if state.best.metrics else None,
        "best_node_id": state.best.node_id,
        "iterations": attempted,
        "max_iterations": max_iterations,
        "wall_clock_seconds": elapsed_seconds,
        "total_input_tokens": input_tokens,
        "total_output_tokens": output_tokens,
        "manual_interventions": 0,
        "hidden_test_access": False,
        "nodes": [
            {
                "node_id": node.node_id,
                "parent_id": node.parent_id,
                "status": node.status,
                "title": node.title,
                "hypothesis": node.hypothesis,
                "validation": asdict(node.metrics) if node.metrics else None,
            }
            for node in state.nodes.values()
        ],
        "final_submission": (
            str(final_submission.relative_to(root))
            if final_submission is not None
            else None
        ),
    }


def run_agent(
    root: Path,
    data_directory: Path,
    log_directory: Path,
    *,
    max_iterations: int = 50,
    wall_clock_seconds: float = 6 * 60 * 60,
    timeout_seconds: float = 900.0,
    client: OpenAI | None = None,
) -> AgentSummary:
    """Run baseline, tree search, code generation, repair, and submission."""
    if max_iterations < 1:
        raise ValueError("max_iterations must be positive")
    root = root.resolve()
    data_directory = data_directory.resolve()
    run_directory = log_directory.resolve() / datetime.now(UTC).strftime(
        "%Y%m%dT%H%M%SZ"
    )
    node_directory = run_directory / "nodes"
    node_directory.mkdir(parents=True, exist_ok=True)
    environment = build_environment(root)
    started = time.monotonic()
    input_tokens = 0
    output_tokens = 0
    stopped_reason = "iteration_cap"
    state = initialize_search(
        root,
        data_directory,
        run_directory,
        node_directory,
        environment=environment,
        timeout_seconds=timeout_seconds,
    )
    attempted = 0

    for iteration in range(1, max_iterations + 1):
        remaining = wall_clock_seconds - (time.monotonic() - started)
        if remaining <= 0:
            stopped_reason = "wall_clock_cap"
            break
        outcome = run_search_iteration(
            iteration,
            state,
            run_directory,
            node_directory,
            root=root,
            data_directory=data_directory,
            environment=environment,
            timeout_seconds=min(timeout_seconds, remaining),
            client=client,
        )
        input_tokens += outcome.input_tokens
        output_tokens += outcome.output_tokens
        if outcome.stop_reason is not None:
            stopped_reason = outcome.stop_reason
            break
        attempted += 1
        if has_converged(state.scores):
            stopped_reason = "converged"
            break

    try:
        final_submission = finalize_submission(
            state.best,
            run_directory,
            root=root,
            data_directory=data_directory,
            environment=environment,
            timeout_seconds=timeout_seconds,
        )
    except (OSError, RuntimeError, subprocess.TimeoutExpired) as error:
        final_submission = None
        stopped_reason = f"submission_failure: {error}"
    write_log(
        run_directory / "manifest.json",
        build_manifest(
            state,
            root=root,
            stopped_reason=stopped_reason,
            attempted=attempted,
            max_iterations=max_iterations,
            elapsed_seconds=time.monotonic() - started,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            final_submission=final_submission,
        ),
    )
    return AgentSummary(
        best_validation=state.best.metrics or state.baseline,
        iterations=attempted,
        manual_interventions=0,
        total_input_tokens=input_tokens,
        total_output_tokens=output_tokens,
        run_directory=run_directory,
        final_submission=final_submission,
    )
